### ISSUE TITLE
Sobre los parciales: Incompleta

### ISSUE THREAD

**Issue by robrui** [dds-jv/dds-jv.github.io#26]
La página _[Sobre los Parciales](https://dds-jv.github.io/pautas/sobre-los-parciales)_, quedó incompleta.
Por otra parte, figura en uno de los ítems "ver mail de Ariel". ¿No se podrá enlazar a la sección _Sobre los Trabajos Prácticos_?

**Comment by flbulgarelli** [comment]
> ¿No se podrá enlazar a la sección Sobre los Trabajos Prácticos?

Sip.

Lo otro hay que _emprolijarlo_, al menos
