### ISSUE TITLE
Agergar entrada de cursadas anteriores donde se muestre bitácora y planificación

### ISSUE THREAD

**Issue by nanderson87** [dds-jv/dds-jv.github.io#28]
Actualmente la bitácora muestra la planificación del año actual y se va mostrando mientras suceden las clases. 

Tal vez es conveniente agregar una entrada para tener acceso a bitacoras de años anteriores pensando en los que estan preparando el final o simplemente quieren ver un tema en particular. Es verdad que en la sección de apuntes/bibliografia seguramente lo puedan encontrar  pero viendo las bitácoras y la planificación por ahí es más sencillo recordad que temas se fueron tocando y relacionarlos con los apuntes que pueda tener cada uno en su cuaderno. 

Creo que este tema lo comentamos con @flbulgarelli hace unos días porque justo se dio que un alumno le preguntó donde podía encontrar "x" tema. 

Les parece util implementar algo del estilo o creen con los apuntes nos alcanza?

**Comment by nanderson87** [comment]
Para empezar a llevar a cabo estas idea, se crea [PR](https://github.com/dds-jv/dds-jv.github.io/pull/29)

**Comment by nanderson87** [comment]
Cambios mergeados en [PR29](https://github.com/dds-jv/dds-jv.github.io/pull/29).

**Comment by flbulgarelli** [comment]
Perfecto!
